title: VARSIT-e
description: Surgical video library

# Use the GitHub Pages "Slate" theme
remote_theme: pages-themes/slate@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation (shows up in header)
header_pages:
  - about.md
  - library/index.md
  - events/index.md
  - education/index.md
  - research/index.md

# Collections for your videos
collections:
  videos:
    output: true
    permalink: /library/:name/
